package com.microsoft.did.sdk.registrars

import com.microsoft.did.sdk.identifier.IdentifierDocument

/**
 * @interface defining methods and properties
 * to be implemented by specific registration methods.
 */
interface IRegistrar {

    /**
     * Registers the identifier document on the ledger
     * returning the identifier generated by the registrar.
     * @param identifierDocument to register.
     * @param signingKeyReference reference to the key to be used for signing request.
     */
    open fun register(identifierDocument: IdentifierDocument, signingKeyReference: String?)
}