package com.microsoft.did.sdk.registrars

import com.microsoft.did.sdk.crypto.CryptoOperations
import com.microsoft.did.sdk.identifier.document.IdentifierDocument

/**
 * @interface defining methods and properties
 * to be implemented by specific registration methods.
 */
abstract class IRegistrar {

    /**
     * Registers the identifier document on the ledger
     * returning the identifier generated by the registrar.
     * @param identifierDocument to be registered.
     * @param signingKeyReference reference to the key to be used for signing request.
     */
    abstract suspend fun register(document: RegistrationDocument, signatureKeyRef: String, crypto: CryptoOperations): IdentifierDocument
}