package com.microsoft.did.sdk.registrars

import com.microsoft.did.sdk.crypto.CryptoOperations
import com.microsoft.did.sdk.crypto.keyStore.IKeyStore
import com.microsoft.did.sdk.identifier.IdentifierDocument

/**
 * Registrar implementation for the Sidetree network
 * @class
 * @implements IRegistrar
 * @param url to the registration endpoint
 * @param cryptoOperations
 */
class SidetreeRegistrar(url: String, cryptoOperations: CryptoOperations): IRegistrar {

    /**
     * Registers the identifier document on the ledger
     * returning the identifier generated by the registrar.
     * @param identifierDocument to register.
     * @param signingKeyReference reference to the key to be used for signing request.
     */
    override fun register(identifierDocument: IdentifierDocument, signingKeyReference: String?) {
        throw Error("Not Implemented")
//        val client = HttpClient(HttpClientEngine) {
//            install(JsonFeature) {
//                serializer = KotlinxSerializer()
//            }
//        }
    }

    /**
     * Sign the Registration Payload
     * @param bodyString original payload to sign.
     * @param signingKeyReference reference to signature key if not default key.
     */
    private fun signPayload(bodyString: String, signingKeyReference: String?) {}


}