package com.microsoft.did.sdk.registrars

import com.microsoft.did.sdk.crypto.keyStore.IKeyStore
import com.microsoft.did.sdk.identifier.IdentifierDocument

/**
 * Registrar implementation for the Sidetree network
 * @class
 * @implements IRegistrar
 * @param url to the registration endpoint
 * @param keyStore
 */
class SidetreeRegistrar(url: String, keyStore: IKeyStore): IRegistrar {

    /**
     * Registers the identifier document on the ledger
     * returning the identifier generated by the registrar.
     * @param identifierDocument to register.
     * @param signingKeyReference reference to the key to be used for signing request.
     */
    override fun register(identifierDocument: IdentifierDocument, signingKeyReference: String?) {
        throw Error("Not Implemented")
    }
}