/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import Identifier from '../Identifier';
import IdentifierDocument from '../IdentifierDocument';
import { DidKey } from '@decentralized-identity/did-common-typescript';

/**
 * Interface defining methods and properties to
 * be implemented by specific registration methods.
 */
export default interface IRegistrar {
  /**
   * Registers the identifier document on the ledger
   * returning the identifier generated by the registrar.
   * @param identifierDocument to register.
   * @param didKey Public key to add to the document.
   */
  register (identifierDocument: IdentifierDocument, didKey: DidKey): Promise<Identifier>;

  /**
   * Uses the specified input for generating
   * an identifier reference, but does not register
   * with a ledger.
   * @param input generating the identifier.
   */
  generateIdentifier (input: any): Promise<Identifier>;
}
