/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import Identifier from '../Identifier';
import IdentifierDocument from '../IdentifierDocument';

/**
 * Interface defining methods and properties to
 * be implemented by specific registration methods.
 */
export default interface Registrar {
  /**
   * Registers the identifier document on the ledger
   * returning the identifier generated by the registrar.
   * @param identifierDocument to register.
   */
  register (identifierDocument: IdentifierDocument): Promise<Identifier>;
}
